import { date, decimal, integer, jsonb, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { zameen } from './_schema.js';
import { entities } from './core.js';

export const buyersCrm = zameen.table('buyers_crm', {
  id: uuid('id').primaryKey().defaultRandom(),
  entityId: uuid('entity_id').notNull().references(() => entities.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  nameUr: text('name_ur'),
  buyerType: text('buyer_type').notNull(),
  contactPerson: text('contact_person'),
  phone: text('phone'),
  altPhone: text('alt_phone'),
  email: text('email'),
  cnic: text('cnic'),
  ntn: text('ntn'),
  address: text('address'),
  location: jsonb('location'),
  paymentTermsDays: integer('payment_terms_days'),
  creditLimitPkr: decimal('credit_limit_pkr', { precision: 14, scale: 2 }),
  notes: text('notes'),
  status: text('status').notNull().default('active'),
  blacklistedReason: text('blacklisted_reason'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const salesOpportunities = zameen.table('sales_opportunities', {
  id: uuid('id').primaryKey().defaultRandom(),
  entityId: uuid('entity_id').notNull().references(() => entities.id, { onDelete: 'cascade' }),
  buyerId: uuid('buyer_id').references(() => buyersCrm.id),
  buyerNameFreeform: text('buyer_name_freeform'),
  cropCode: text('crop_code').notNull(),
  estimatedKg: decimal('estimated_kg', { precision: 14, scale: 2 }).notNull(),
  targetPricePerKgPkr: decimal('target_price_per_kg_pkr', { precision: 12, scale: 2 }),
  stage: text('stage').notNull().default('lead'),
  expectedCloseDate: date('expected_close_date'),
  actualCloseDate: date('actual_close_date'),
  winProbabilityPct: integer('win_probability_pct'),
  source: text('source'),
  lostReason: text('lost_reason'),
  notes: text('notes'),
  createdBy: uuid('created_by'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const forwardContracts = zameen.table('forward_contracts', {
  id: uuid('id').primaryKey().defaultRandom(),
  entityId: uuid('entity_id').notNull().references(() => entities.id, { onDelete: 'cascade' }),
  buyerId: uuid('buyer_id').notNull().references(() => buyersCrm.id),
  contractNumber: text('contract_number').notNull(),
  signedOn: date('signed_on').notNull(),
  cropCode: text('crop_code').notNull(),
  committedKg: decimal('committed_kg', { precision: 14, scale: 2 }).notNull(),
  agreedPricePerKgPkr: decimal('agreed_price_per_kg_pkr', { precision: 12, scale: 2 }).notNull(),
  deliveryWindowStart: date('delivery_window_start').notNull(),
  deliveryWindowEnd: date('delivery_window_end').notNull(),
  deliveryPoint: text('delivery_point'),
  paymentTerms: text('payment_terms'),
  advanceReceivedPkr: decimal('advance_received_pkr', { precision: 14, scale: 2 }).notNull().default('0'),
  advanceReceivedOn: date('advance_received_on'),
  qualitySpecs: jsonb('quality_specs'),
  penaltyClause: text('penalty_clause'),
  status: text('status').notNull().default('open'),
  deliveredKg: decimal('delivered_kg', { precision: 14, scale: 2 }).notNull().default('0'),
  deliveredPkr: decimal('delivered_pkr', { precision: 14, scale: 2 }).notNull().default('0'),
  contractDocUrl: text('contract_doc_url'),
  approvalRequestId: uuid('approval_request_id'),
  createdBy: uuid('created_by'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const contractDeliveries = zameen.table('contract_deliveries', {
  id: uuid('id').primaryKey().defaultRandom(),
  contractId: uuid('contract_id').notNull().references(() => forwardContracts.id, { onDelete: 'cascade' }),
  deliveredOn: date('delivered_on').notNull(),
  kg: decimal('kg', { precision: 14, scale: 2 }).notNull(),
  pkr: decimal('pkr', { precision: 14, scale: 2 }).notNull(),
  produceLotIds: jsonb('produce_lot_ids').$type<string[]>().notNull().default([]),
  deliveryNoteUrl: text('delivery_note_url'),
  notes: text('notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});
