import {
  Masthead,
  SectionDivider,
  StatBlock,
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  Pkr,
  ChartCard,
} from '@zameen/ui';

const DIESEL_30D = [
  { day: 'Apr 18', litres: 142 },
  { day: 'Apr 25', litres: 168 },
  { day: 'May 02', litres: 195 },
  { day: 'May 09', litres: 184 },
  { day: 'May 16', litres: 211 },
];

const TODAY_TASKS = [
  { code: 'F3', title: 'Apply urea top-dress', crew: 'Akram + 3' },
  { code: 'F7', title: 'Aphid scouting walk', crew: 'Shahid' },
  { code: 'F11', title: 'Berseem cut 2', crew: 'Yousaf + 5' },
  { code: 'F2', title: 'Tubewell 1 service', crew: 'Mechanic Imran' },
];

export default function DashboardHome() {
  return (
    <div>
      <Masthead section="Overview" />

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <StatBlock label="Pending approvals" value="3" caption="2 with Farm Manager · 1 with MF" delta={{ value: -1, label: 'vs yesterday' }} />
        <StatBlock label="Workers present" value={<><span>18</span><span className="text-2xl text-[var(--fg-muted)] ml-1">/22</span></>} caption="Geofence-verified" />
        <StatBlock label="Diesel stock" value={<><span>3,420</span><span className="text-xl text-[var(--fg-muted)] ml-1">L</span></>} caption="Main Tank" delta={{ value: 2.1 }} />
        <StatBlock label="Cash on hand" value={<Pkr value={2_840_500} mode="lac_crore" />} caption="Soneri current" delta={{ value: -8.4 }} />
      </div>

      <SectionDivider label="Today" />

      <div className="grid gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Tasks in motion</CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <ul>
              {TODAY_TASKS.map((t, idx) => (
                <li
                  key={t.code}
                  className={`flex items-baseline justify-between px-5 py-3 ${idx > 0 ? 'border-t border-[var(--border)]' : ''}`}
                >
                  <span className="flex items-baseline gap-3">
                    <span className="smallcaps text-[var(--accent)]">{t.code}</span>
                    <span className="text-[var(--fg)]">{t.title}</span>
                  </span>
                  <span className="tabular text-[0.78rem] text-[var(--fg-muted)]">{t.crew}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        <ChartCard
          title="Diesel consumption — last 30 days"
          data={DIESEL_30D}
          xKey="day"
          yKey="litres"
          unit="litres per week"
        />
      </div>

      <SectionDivider label="Field activity" />

      <div className="grid gap-4 md:grid-cols-4">
        {['F3 Wheat', 'F7 Wheat', 'F11 Berseem', 'F15 Fallow'].map((label) => (
          <Card key={label}>
            <CardContent className="space-y-3">
              <div className="smallcaps">{label}</div>
              <div className="aspect-[4/3] rounded-[10px] bg-gradient-to-br from-[var(--surface-2)] to-[var(--bg-2)] border border-[var(--border)]" />
              <div className="tabular text-xs text-[var(--fg-muted)]">6.2 acre · vegetative stage</div>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="mt-12 pt-6 border-t border-[var(--border)] flex items-center justify-between text-xs text-[var(--fg-subtle)]">
        <span>Generated by Zameen</span>
        <span className="tabular">{new Date().toLocaleString('en-GB', { hour: '2-digit', minute: '2-digit' })}</span>
      </div>
    </div>
  );
}
