import * as React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// Brand palette. Deep green + ochre on cream. Matches Rupafab Agri.
export const BRAND = {
  green: '#1f4d2b',
  greenSoft: '#386c47',
  ochre: '#b9802c',
  ink: '#1a1a1a',
  inkMuted: '#5a5a5a',
  rule: '#cfc6b6',
  paper: '#fbf6ec',
  paper2: '#f1ead8',
  danger: '#a3331a',
  success: '#2a6b3a',
} as const;

let fontsRegistered = false;
function registerFontsOnce(): void {
  if (fontsRegistered) return;
  fontsRegistered = true;
  // Use Google CDN. @react-pdf supports remote ttf.
  try {
    Font.register({
      family: 'Inter',
      fonts: [
        { src: 'https://fonts.gstatic.com/s/inter/v18/UcCO3FwrK3iLTeHuS_nVMrMxCp50ojIa1ZL7.ttf', fontWeight: 400 },
        { src: 'https://fonts.gstatic.com/s/inter/v18/UcCO3FwrK3iLTeHuS_nVMrMxCp50ojIa1ZL7.ttf', fontWeight: 600 },
      ],
    });
    Font.register({
      family: 'JetBrainsMono',
      fonts: [
        { src: 'https://fonts.gstatic.com/s/jetbrainsmono/v22/tDbY2o-flEEny0FZhsfKu5WU4zr3E_BX0PnT8RD8yKxjPVmUsaaDhw.ttf', fontWeight: 400 },
      ],
    });
  } catch {
    // Network unavailable. @react-pdf falls back to Helvetica.
  }
}

export const styles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingBottom: 48,
    paddingHorizontal: 36,
    fontFamily: 'Inter',
    fontSize: 9,
    color: BRAND.ink,
    backgroundColor: '#ffffff',
  },
  pageLandscape: {
    paddingTop: 32,
    paddingBottom: 44,
    paddingHorizontal: 32,
    fontFamily: 'Inter',
    fontSize: 9,
    color: BRAND.ink,
    backgroundColor: '#ffffff',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    borderBottomWidth: 1.5,
    borderBottomColor: BRAND.green,
    paddingBottom: 8,
    marginBottom: 14,
  },
  brand: { fontSize: 14, fontWeight: 600, color: BRAND.green, letterSpacing: 1 },
  brandSub: { fontSize: 8, color: BRAND.ochre, letterSpacing: 2, marginTop: 2 },
  title: { fontSize: 11, fontWeight: 600, color: BRAND.ink },
  metaCol: { flexDirection: 'column', alignItems: 'flex-end' },
  metaLine: { fontSize: 8, color: BRAND.inkMuted },
  footer: {
    position: 'absolute',
    left: 36,
    right: 36,
    bottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 7.5,
    color: BRAND.inkMuted,
    borderTopWidth: 0.5,
    borderTopColor: BRAND.rule,
    paddingTop: 6,
  },
  section: { marginTop: 14, marginBottom: 8 },
  sectionTitle: {
    fontSize: 8,
    letterSpacing: 1.5,
    color: BRAND.green,
    fontWeight: 600,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  table: { width: '100%', borderTopWidth: 0.5, borderTopColor: BRAND.rule },
  trHead: {
    flexDirection: 'row',
    backgroundColor: BRAND.paper2,
    borderBottomWidth: 0.5,
    borderBottomColor: BRAND.rule,
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  tr: {
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderBottomColor: BRAND.rule,
    paddingVertical: 3,
    paddingHorizontal: 4,
  },
  th: { fontSize: 7.5, fontWeight: 600, color: BRAND.green, letterSpacing: 0.5, textTransform: 'uppercase' },
  td: { fontSize: 8.5, color: BRAND.ink },
  tdMono: { fontSize: 8, fontFamily: 'JetBrainsMono', color: BRAND.ink },
  tdMoney: { fontSize: 8.5, color: BRAND.ink, textAlign: 'right' },
  totalRow: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: BRAND.green,
    paddingVertical: 5,
    paddingHorizontal: 4,
    backgroundColor: BRAND.paper,
  },
  totalLabel: { fontSize: 8.5, fontWeight: 600, color: BRAND.green },
  note: { fontSize: 8, color: BRAND.inkMuted, marginTop: 6, lineHeight: 1.4 },
  badgeOchre: {
    fontSize: 7,
    color: BRAND.ochre,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
});

export interface ReportHeaderProps {
  title: string;
  entityName: string;
  period: string;
  generatedAt: Date;
  generatedBy: string;
}

export function ReportHeader({ title, entityName, period, generatedAt, generatedBy }: ReportHeaderProps) {
  return (
    <View style={styles.headerRow} fixed>
      <View>
        <Text style={styles.brand}>RUPAFAB AGRI</Text>
        <Text style={styles.brandSub}>ZAMEEN OPERATIONS</Text>
        <Text style={[styles.title, { marginTop: 6 }]}>{title}</Text>
      </View>
      <View style={styles.metaCol}>
        <Text style={styles.metaLine}>{entityName}</Text>
        <Text style={styles.metaLine}>Period: {period}</Text>
        <Text style={styles.metaLine}>
          Generated {fmtPdfDate(generatedAt)} by {generatedBy}
        </Text>
      </View>
    </View>
  );
}

export function ReportFooter() {
  return (
    <View style={styles.footer} fixed>
      <Text>Generated by Zameen</Text>
      <Text
        render={({ pageNumber, totalPages }: { pageNumber: number; totalPages: number }) =>
          `Page ${pageNumber} of ${totalPages}`
        }
      />
    </View>
  );
}

export interface ReportShellProps {
  title: string;
  entityName: string;
  period: string;
  generatedAt?: Date;
  generatedBy: string;
  orientation?: 'portrait' | 'landscape';
  children: React.ReactNode;
}

export function ReportShell({
  title,
  entityName,
  period,
  generatedAt,
  generatedBy,
  orientation = 'portrait',
  children,
}: ReportShellProps) {
  registerFontsOnce();
  const at = generatedAt ?? new Date();
  return (
    <Document
      title={`${title} (${period})`}
      author={generatedBy}
      creator="Zameen"
      producer="Zameen"
      subject={`${entityName}, ${period}`}
    >
      <Page size="A4" orientation={orientation} style={orientation === 'landscape' ? styles.pageLandscape : styles.page}>
        <ReportHeader title={title} entityName={entityName} period={period} generatedAt={at} generatedBy={generatedBy} />
        <View>{children}</View>
        <ReportFooter />
      </Page>
    </Document>
  );
}

export function fmtPdfDate(d: Date | string | null | undefined): string {
  if (!d) return '';
  const dt = typeof d === 'string' ? new Date(d) : d;
  return dt.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}

export function fmtPdfDateTime(d: Date | string | null | undefined): string {
  if (!d) return '';
  const dt = typeof d === 'string' ? new Date(d) : d;
  return dt.toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
}

export function fmtPdfMoney(n: number | string | null | undefined): string {
  if (n === null || n === undefined || n === '') return '';
  const num = typeof n === 'string' ? Number(n) : n;
  if (!Number.isFinite(num)) return '';
  return `Rs. ${new Intl.NumberFormat('en-PK', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(num)}`;
}

export function fmtPdfQty(n: number | string | null | undefined, frac = 2): string {
  if (n === null || n === undefined || n === '') return '';
  const num = typeof n === 'string' ? Number(n) : n;
  if (!Number.isFinite(num)) return '';
  return new Intl.NumberFormat('en-PK', { minimumFractionDigits: frac, maximumFractionDigits: frac }).format(num);
}

export interface ColumnSpec {
  key: string;
  label: string;
  width: number; // percentage
  align?: 'left' | 'right' | 'center';
  mono?: boolean;
}

export interface SimpleTableProps {
  columns: ColumnSpec[];
  rows: Array<Record<string, string | number | null | undefined>>;
  totals?: Record<string, string | number | null | undefined>;
  totalsLabel?: string;
}

export function SimpleTable({ columns, rows, totals, totalsLabel = 'Total' }: SimpleTableProps) {
  return (
    <View style={styles.table}>
      <View style={styles.trHead}>
        {columns.map((c) => (
          <Text
            key={c.key}
            style={[
              styles.th,
              {
                width: `${c.width}%`,
                textAlign: c.align ?? 'left',
              },
            ]}
          >
            {c.label}
          </Text>
        ))}
      </View>
      {rows.length === 0 ? (
        <View style={styles.tr}>
          <Text style={[styles.td, { width: '100%', color: BRAND.inkMuted, fontStyle: 'italic' }]}>
            No data in this period.
          </Text>
        </View>
      ) : (
        rows.map((r, i) => (
          <View key={i} style={styles.tr} wrap={false}>
            {columns.map((c) => {
              const raw = r[c.key];
              const text = raw === null || raw === undefined ? '' : String(raw);
              return (
                <Text
                  key={c.key}
                  style={[
                    c.mono ? styles.tdMono : styles.td,
                    {
                      width: `${c.width}%`,
                      textAlign: c.align ?? 'left',
                    },
                  ]}
                >
                  {text}
                </Text>
              );
            })}
          </View>
        ))
      )}
      {totals ? (
        <View style={styles.totalRow}>
          {columns.map((c, i) => {
            const v = totals[c.key];
            const text = i === 0 ? totalsLabel : v === null || v === undefined ? '' : String(v);
            return (
              <Text
                key={c.key}
                style={[
                  styles.totalLabel,
                  {
                    width: `${c.width}%`,
                    textAlign: c.align ?? 'left',
                  },
                ]}
              >
                {text}
              </Text>
            );
          })}
        </View>
      ) : null}
    </View>
  );
}

export function SectionTitlePdf({ children }: { children: React.ReactNode }) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{children}</Text>
    </View>
  );
}
